name: Deploy Frontend to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy index.html to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: 3.27.221.101
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "frontend/index.html"
        target: "/usr/share/nginx/html"

    - name: Restart Nginx
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 3.27.221.101
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo systemctl restart nginx
